name: ML Recommendation Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"   # 4 AM IST

jobs:
  run-ml-pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: 📦 Checkout
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📚 Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pandas sqlalchemy psycopg2-binary

      - name: 📂 Debug Files
        run: ls -R

      - name: 🚀 Run Pipeline
        env:
          EVENTS_DB_URL: ${{ secrets.EVENTS_DB_URL }}
          PRODUCT_DB_URL: ${{ secrets.PRODUCT_DB_URL }}
          RECO_DB_URL: ${{ secrets.RECO_DB_URL }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_CC: ${{ secrets.MAIL_CC }}
        run: |
          echo "🚀 Running pipeline..."
          python pipeline/run_pipeline.py
